=== bfritz/jbidibc/trunk/jbidibc-exchange/src/main/resources/xsd/vendor_cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.bidib.org/vendorcv" 
	xmlns:vendorcv="http://www.bidib.org/vendorcv" 
	elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

	<xsd:complexType name="VersionInfoType">
		<xsd:attribute name="version" type="xsd:string" use="required" />
		<xsd:attribute name="LastUpdate" type="xsd:string" use="required" />
		<xsd:attribute name="author" type="xsd:string" use="required" />
		<xsd:attribute name="PID1" type="xsd:string" use="required"/>
		<xsd:attribute name="PID2" type="xsd:string" use="required"/>
		<xsd:attribute name="Vendor" type="xsd:string" use="required"/>
		<xsd:attribute name="description" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="TemplatesType">
		<xsd:choice>
			<xsd:element ref="vendorcv:LED" />
			<xsd:element ref="vendorcv:Servo" />
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="LED">
		<xsd:sequence>
			<xsd:element ref="vendorcv:CV" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Servo">
		<xsd:sequence>
			<xsd:element ref="vendorcv:CV" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

<!-- 
	<xsd:complexType name="TemplatesType">
		<xsd:sequence>
			<xsd:element ref="vendorcv:Template" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TemplateType" abstract="true">
	</xsd:complexType>

	<xsd:complexType name="LED">
		<xsd:complexContent>
			<xsd:extension base="vendorcv:TemplateType">
				<xsd:sequence>
					<xsd:element ref="vendorcv:CV" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
 -->
	<xsd:complexType name="CV">
		<xsd:attribute name="number" type="xsd:int" />
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="mode" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="CVDefinitionType">
	</xsd:complexType>

	<xsd:element name="LED" type="vendorcv:LED" />
	<xsd:element name="Servo" type="vendorcv:Servo" />
	<xsd:element name="Version" type="vendorcv:VersionInfoType" />
	<xsd:element name="Templates" type="vendorcv:TemplatesType" />
	<xsd:element name="CVDefinition" type="vendorcv:CVDefinitionType" />
<!-- 	<xsd:element name="Template" type="vendorcv:TemplateType" /> -->
	<xsd:element name="CV" type="vendorcv:CV" />

	<xsd:element name="VendorCV">
		<xsd:annotation>
			<xsd:documentation>VendorCV definition</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="vendorcv:Version" />
				<xsd:element ref="vendorcv:Templates" />
				<xsd:element ref="vendorcv:CVDefinition" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
<!-- 	<xsd:element name="VendorCV" type="vendorcv:VendorCVType"/> -->
	

</xsd:schema>

=== bfritz/jbidibc/trunk/jbidibc-exchange/src/test/resources/xsd/XSL-Output-OneOC.xml
<?xml version="1.0" encoding="UTF-8"?>
<VendorCV xmlns="http://www.bidib.org/vendorcv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bidib.org/vendorcv vendor_cv.xsd">
    <Version version="0.1" LastUpdate="20130519" author="Tillner, Andreas" PID1="119" PID2="000" Vendor="013" description="OneOC (20x OC-Input) - BiDiBOne AddOn"></Version>
    <CVDefinition>
        <Basis>
            <CV number="51" type="Byte" min="0" max="2" next="-" values="0;1;2" mode="w" descde="0 = keine Anzeige, 1 = LED Anzeige, 2 = DOGM 3x16 Display" descen="0 = no display, 1 = LED line, 2 = DOGM 3x16 Display"/>
            <CV number="52" type="Byte" min="-" max="-" next="-" mode="w" values="87;120;160" descde="Masstab" descen="Scale"/>
        </Basis>
        <SectorDefinition number="1">
            <CV number="53" type="Byte" min="0" max="255" next="1;53" mode="w" values="-" descde="Länge der Messstrecke 1 in mm (lowbyte)(CV53+CV54*256)" descen="Length of measuring 1 track in mm (lowbyte)(CV53+CV54*256)"/>
            <CV number="54" type="Byte" min="0" max="255" next="h;53" mode="w" values="-" descde="Länge der Messstrecke 1 in mm (highbyte)(CV55+CV56*256)" descen="Length of measuring 1 track in mm (highbyte)(CV55+CV56*256)"/>
            <CV number="55" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 1" descen="Startdetector of the measuring track 1"/>
            <CV number="56" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 1" descen="Enddetector of the measuring track 1"/>
        </SectorDefinition>
        <SectorDefinition number="2">
            <CV number="57" type="Byte" min="0" max="255" next="-" mode="w" values="l;54" descde="Länge der Messstrecke 2 in mm (lowbyte)(CV57+CV58*256)" descen="Length of measuring 2 track in mm (lowbyte)(CV57+CV58*256)"/>
            <CV number="58" type="Byte" min="0" max="255" next="h;53" mode="w" values="-" descde="Länge der Messstrecke 2 in mm (highbyte)(CV57+CV58*256)" descen="Length of measuring 2 track in mm (highbyte)(CV57+CV58*256)"/>
            <CV number="59" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 2" descen="Startdetector of measuring track 2"/>
            <CV number="60" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 2" descen="Enddetector of measuring track 2"/>
        </SectorDefinition>
        <SectorDefinition number="3">
            <CV number="61" type="Byte" min="0" max="255" next="-" mode="w" values="l;54" descde="Länge der Messstrecke 3 in mm (lowbyte)(CV61+CV62*256)" descen="Length of measuring 3 track in mm (lowbyte)(CV61+CV62*256)"/>
            <CV number="62" type="Byte" min="0" max="255" next="h;53" mode="w" values="-" descde="Länge der Messstrecke 3 in mm (highbyte)(CV61+CV62*256)" descen="Length of measuring 3 track in mm (highbyte)(CV61+CV62*256)"/>
            <CV number="63" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 3" descen="Startdetector of measuring track 3"/>
            <CV number="64" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 3" descen="Enddetector of measuring track 3"/>
        </SectorDefinition>
        <SectorDefinition number="4">
            <CV number="65" type="Byte" min="0" max="255" next="-" mode="w" values="l;66" descde="Länge der Messstrecke 4 in mm (lowbyte)(CV65+CV66*256)" descen="Length of measuring 4 track in mm (lowbyte)(CV65+CV66*256)"/>
            <CV number="66" type="Byte" min="0" max="255" next="h;65" mode="w" values="-" descde="Länge der Messstrecke 4 in mm (highbyte)(CV65+CV66*256)" descen="Length of measuring 4 track in mm (highbyte)(CV65+CV66*256)"/>
            <CV number="67" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 4" descen="Startdetector of measuring track 4"/>
            <CV number="68" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 4" descen="Enddetector of measuring track 4"/>
        </SectorDefinition>
        <SectorDefinition number="5">
            <CV number="69" type="Byte" min="0" max="255" next="-" mode="w" values="l;70" descde="Länge der Messstrecke 5 in mm (lowbyte)(CV69+CV70*256)" descen="Length of measuring 5 track in mm (lowbyte)(CV69+CV70*256)"/>
            <CV number="70" type="Byte" min="0" max="255" next="h;69" mode="w" values="-" descde="Länge der Messstrecke 5 in mm (highbyte)(CV69+CV70*256)" descen="Length of measuring 5 track in mm (highbyte)(CV69+CV70*256)"/>
            <CV number="71" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 5" descen="Startdetector of measuring track 5"/>
            <CV number="72" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 5" descen="Enddetector of measuring track 5"/>
        </SectorDefinition>
        <SectorDefinition number="6">
            <CV number="73" type="Byte" min="0" max="255" next="-" mode="w" values="l;54" descde="Länge der Messstrecke 6 in mm (lowbyte)(CV55+CV56*256)" descen="Length of measuring 6 track in mm (lowbyte)(CV55+CV56*256)"/>
            <CV number="74" type="Byte" min="0" max="255" next="h;53" mode="w" values="-" descde="Länge der Messstrecke 6 in mm (highbyte)(CV55+CV56*256)" descen="Length of measuring 6 track in mm (highbyte)(CV55+CV56*256)"/>
            <CV number="75" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Startmelder der Messstrecke 6" descen="Startdetector of measuring track 6"/>
            <CV number="76" type="Byte" min="0" max="19" next="-" mode="w" values="-" descde="Endmelder der Messstrecke 6" descen="Enddetector of measuring track 6"/>
        </SectorDefinition>
    </CVDefinition>
</VendorCV>

=== bfritz/jbidibc/trunk/jbidibc-exchange/src/test/resources/xsd/XSL-Output-S88-Bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<VendorCV xmlns="http://www.bidib.org/jbidibc/vendorcv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bidib.org/vendorcv vendor_cv.xsd">
    <Version version="0.1" LastUpdate="20130515" author="BiDiB-Mustermann" PID1="107" PID2="000" Vendor="013" description="BiDiB-s88-Bridge"/>
    <CVDefinition>
        <Basis>
            <CV number="1" type="Byte" min="0" max="255" low="-" high="-" values="-" mode="ro" descde="vendor_id" descen="vendor_id"/>
            <CV number="2" type="Byte" min="0" max="255" low="-" high="-" values="-" mode="ro" descde="hw_id" descen="hw_id"/>
            <CV number="3" type="Int" min="0" max="255" low="3" high="4" values="-" mode="rw" descde="hw_serial_low" descen="hw_serial_low"/>
            <CV number="4" type="Int" min="0" max="255" low="3" high="4" values="-" mode="rw" descde="hw_serial_high" descen="hw_serial_high"/>
            <CV number="5" type="Byte" min="-" max="-" low="-" high="-" values="2;4;6;8;10;12;16" mode="rw" descde="s88_size" descen="s88_size"/>
            <CV number="6" type="Byte" min="0" max="255" low="-" high="-" values="-" mode="rw" descde="s88_clk_timing" descen="s88_clk_timing"/>
        </Basis>
    </CVDefinition>
</VendorCV>
